### ISSUE TITLE
End to end evaluation

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [wellcometrust/reach#315]
UPDATE 12th May 2020 - Liz will be picking this up again.

I wanted to create a record here of steps I am following to run an end-to-end evaluation as it is starting to get somewhat complicated! 

DRP = deep reference parser

- [x] Prepare validation data
  - [x] Label data with IOBE schema for reference splitting with which to train DRP
  - [x] Split data into train/test/validate sets for model training and evaluation (note that this takes place at the document level, so there is no data leakage from train to test/validate)
  - [x] Take the validation set from the above, and use the prodigy `_input_hash` to match back in the reach document id.
  - [x] Manually annotate the titles from the documents in the validation data using prodigy.
  - [x] Extract titles from spans labelled in prodigy yielding a [{'document id': '<title>'}, ...] jsonl
  - [x] Run the extracted titles through the fuzzy matcher to get a document id, ultimately yielding: `{'document id': [pmcid0, pmcid1, pmcid2, ...]}` (or equivalent).
  - [x]  Manually check the returned references to confirm quality (`s3://datalabs-data/deep_reference_parser/data/procesed/annotated/2019.10.8_valid_matched_references.jsonl`).
- [x] Evaluate current reach
  - [x] Compare references found in the validation documents with the manually tagged references. __NOTE: This assumes that we continue to find the same documents in the scrape as have been manually tagged. This may not be a good assumption, either because changes in the scraper lead to a change in what documents are found, or because the document is simply no longer available online__.
  - [ ] Fairness evaluation
- [ ] Evaluate DRP
  - [x] Incorporate DRP into existing reach pipeline (replacing the current reference splitter)
  - [ ] Run edited reach pipeline
  - [ ] Compare reference found in validation documents with the manually tagged references. __NOTE: same caveat as above.__
  - [ ] Fairness evaluation - see https://github.com/wellcometrust/datalabs/pull/560/files

The current evaluation data contains:

* 14 unique documents
* 621 manually labelled references
* 102 references for which a valid match was found (similarity threshold = 0.8)
* 85 remaining matches following manual checking.

**Comment by ivyleavedtoadflax** [comment]
> * [ ]  Incorporate DRP into existing reach pipeline (replacing the current reference splitter)

@samdep @jdu do you have any suggestions on the best way to do this?

**Comment by nsorros** [comment]
> > * [ ]   Incorporate DRP into existing reach pipeline (replacing the current reference splitter)
> 
> @SamDepardieu @jdu do you have any suggestions on the best way to do this?

Should we do the same thing we did for the previous iteration and that we are doing now for science tagger? I.e. packaging in a wheel, pushing to s3 etc. This one, we might need to move the model separately as i suspect it is quite big @jdu

**Comment by jdu** [comment]
Honestly I don't have a problem with the models being deployed / packaged in the wheel if they're overly large. If that's the case the only time it will need to be downloaded is at installation time of the package (when we build the container images), however, it does mean that a new generation of the model will need to be released as a new package (and possibly versioned).

Our container images are built on AWS side and they aren't deployed until the build completes (and they're manually pushed from datalabs-infra) so having that model be part of the package isn't a huge deal, we may have to keep an eye on the builds for the containers so that it doesn't timeout on downloading the wheel package, but otherwise I can't really think of any problems with the model being in the wheel itself at the moment other than a lengthier build time potentially.

The only thing I would say is if there is going to be a high volume of churn for the model, where we would need to deploy the model separately from the actual code in the package, then we might need to look at how we deploy this as a resource either in EFS or S3, but if the model isn't going to change that often and most of the time it will be released in lockstep with the wheel then just keep it in the wheel for now.

**Comment by ivyleavedtoadflax** [comment]
Off the top of my head, I think the model weights are likely to be around 250mb, so they are not totally crazy. On the question of where to put it, it would actually be easier right now not to package the model into the wheel, and just download it from s3 at the moment that the container is built, which is roughly equivalent to what happens now when we build the model locally.

**Comment by jdu** [comment]
Yeah that's not horrendous in terms of size, and frankly the speed between S3 and the build service is pretty quick as it's just across amazons internal network. So I would leave it in the wheel for now and if we end up in a situation where we need to update the more and more independently of the wheel then we look at moving it to EFS or something but I think for now dumping it in the wheel isn't really a big deal.

**Comment by ivyleavedtoadflax** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [End to end evaluation of Reach using manually labelled data](https://trello.com/c/GCx4nflF/917-end-to-end-evaluation-of-reach-using-manually-labelled-data)

**Comment by nsorros** [comment]
@ivyleavedtoadflax can you add the fairness evaluation here in the bullet points?

**Comment by ivyleavedtoadflax** [comment]
This is currently blocked by https://github.com/wellcometrust/reach/issues/48

**Comment by lizgzil** [comment]
This is mostly done (not merged yet) in https://github.com/wellcometrust/reach/pull/516
Since the full pipeline hasnt been able to be run yet, we dont have final results yet. But an interim result looks like this (I expect the final result to have found 5/6 of the documents, so the results will be slightly different):
```
{
"doc_metrics": {"found": 4, "missed": 2, "accuracy": 0.67, "total": 6},
"ref_metrics": {"possible": 37, "actual": 46, "found": 28, "missed": 9,
"spurious": 18, "recall": 0.76, "precision": 0.61, "f1": 0.67}, 
"found_docs_ref_metrics": {"possible": 33, "actual": 46, "found": 28,
"missed": 5, "spurious": 18, "recall": 0.85, "precision": 0.61, "f1": 0.71}, 
"gold_refs": "s3://datalabs-data/reach_evaluation/data/sync/2019.10.8-fuzzy-matched-gold-refs-manually-verified.jsonl", 
"reach_refs": "s3://datalabs-dev/combinedmatches/combinedmatches.json.gz", 
"reach_params": null}
```
