### ISSUE TITLE
Some bugs / usability issues in Reach interface ahead of testing 

### ISSUE THREAD

**Issue by aoifespenge** [wellcometrust/reach#423]
Was running through and working on the usability test task and noticing some bugs and issues: 
1) Some of research publications with several citations are coming up as individual results instead of being nested together. 
Search terms: A large proportion of p. falciparum isolates; Worldwide incidence of malaria in 2009
<img width="1233" alt="Screenshot 2020-02-12 at 17 18 56" src="https://user-images.githubusercontent.com/25910370/74367734-44ba1600-4dca-11ea-927c-88813a214fe8.png">

2) Accordion columns not aligned with the research pub search result row. 
<img width="1232" alt="Screenshot 2020-02-12 at 17 20 48" src="https://user-images.githubusercontent.com/25910370/74359955-1a615c00-4dbc-11ea-8de2-0ca0046c5afe.png">
3) No of citation sorting not there. We need this as users will want to find the most cited research. 
4) 'Authors' On policy docs still a field and I think we said we would try get this out. Won't massively impact usability testing if not possible to remove.

**Comment by SamDepardieu** [comment]
@aoifespenge Not sure I can do much about `1. Some of research publications with several citations are coming up as individual results instead of being nested together.`. This happens because we are still relying on file hash to merge pubs together. So even though these have the same title, they have a different document ID. Also as you can see, they have different policy documents attached to it.
I'll look into this, but don't expect this to be fixed for the testing.

Everything else I can fix by the end of the week.

**Comment by aoifespenge** [comment]
Ok I have moved this to progress and I guess I'll open another issue  for no. 1 and add it to the backlog
