### ISSUE TITLE
Publications cited in more than one policy document are not grouped together

### ISSUE THREAD

**Issue by dd207** [wellcometrust/reach#596]
Publications that appear in more than one policy document are not grouped together. 

Feedback has shown that users think the policy citations are duplicates and lose trust in the product. 

![Screenshot 2020-08-20 at 13.33.27.png](https://images.zenhubusercontent.com/5de5100384b91a10d0c5050f/08b550dc-4685-49c5-9fff-5e2f3a8539f9)![Screenshot 2020-08-20 at 13.33.27.png](https://images.zenhubusercontent.com/5de5100384b91a10d0c5050f/d157f79d-8073-4aae-92ff-d263ad253537)

**Comment by SamDepardieu** [comment]
This behaviour is happening in staging too. I'm investigating this

**Comment by SamDepardieu** [comment]
Alright, I had a good look at it, I think this is coming from us grouping reference together during the Fuzzymatching part on their extracted reference id instead of their matched title id. We shouldn't have a hard time fixing that, but we will need to clean/re-populate the database as this issue happens before we insert everything in postgresql.
